name: hyperarrow python wheels

on:
  release:
    types: [created, edited]
  workflow_dispatch:

jobs:
  build-macos:

    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ["3.7"]
        activate-environment: hyperarrow
        channels: conda-forge
    - run: conda install pyarrow
    - name: Install Arrow Libraries
      run: |
        brew install apache-arrow
    - name: Download Hyper Library / Headers
      run: |
        mkdir deps
        pushd deps
        wget https://downloads.tableau.com/tssoftware/tableauhyperapi-cxx-macos-x86_64-release-hyperapi_release_26.0.0.13821.r1fbe38ce.zip -O tableauhyperapi.zip
        unzip tableauhyperapi.zip
        mv tableauhyperapi-cxx-macos-x86_64-release-hyperapi_release_26.0.0.13821.r1fbe38ce tableauhyperapi
        pwd
        ls
        ls tableauhyperapi
        ls tableauhyperapi/share
        ls tableauhyperapi/share/cmake
        popd
    - name: Install boost for test dependency
      run: brew install boost
    - name: Set up out of core build
      run: |
        mkdir build
        cd build
        export TABLEAU_CMAKE_PATH=/Users/runner/work/hyperarrow/hyperarrow/deps/tableauhyperapi/share/cmake
        cmake .. -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl -DOPENSSL_LIBRARIES=/usr/local/opt/openssl/lib
        make
        make test
        make python
    - name: Upload wheel
      uses: actions/upload-artifact@v2
      with:
        name: macos
        path: python/dist/*.whl