name: hyperarrow python wheels

on:
  release:
    types: [created, edited]
  workflow_dispatch:

jobs:
  build-macos:

    runs-on: macos-latest
    env:
      CTEST_OUTPUT_ON_FAILURE: 1
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Print openssl
      run: |
        ls /usr/local/Cellar/
        ls /usr/local/Cellar/openssl@1.1
        ls /usr/local/Cellar/openssl@1.1/1.1.1m
    - name: Install Arrow Libraries
      run: |
        brew install apache-arrow
    - name: Download Hyper Library / Headers
      run: |
        mkdir deps
        pushd deps
        wget https://downloads.tableau.com/tssoftware/tableauhyperapi-cxx-macos-x86_64-release-hyperapi_release_26.0.0.13821.r1fbe38ce.zip -O tableauhyperapi.zip
        unzip tableauhyperapi.zip
        mv tableauhyperapi-cxx-macos-x86_64-release-hyperapi_release_26.0.0.13821.r1fbe38ce tableauhyperapi
    - name: Set up out of core build
      env:
        HYPER_PATH: "/Users/runner/work/hyperarrow/hyperarrow/deps/tableauhyperapi"
        MACOSX_DEPLOYMENT_TARGET: "10.13"
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_PREFIX_PATH="${HYPER_PATH}/share/cmake" \ -DOPENSSL_ROOT_DIR=/usr/local/Cellar/openssl@1.1/1.1.1m -DOPENSSL_INCLUDE_DIR=/usr/local/Cellar/openssl@1.1/1.1.1m/include -DOPENSSL_CRYPTO_LIBRARY=/usr/local/Cellar/openssl@1.1/1.1.1m/lib/libcrypto.dylib -DOPENSSL_SSL_LIBRARY=/usr/local/Cellar/openssl@1.1/1.1.1m/lib/libssl.dylib ..
        make -j"$(sysctl -n hw.logicalcpu)"
        make install
        make python
    - name: Fix wheel (py38)
      run: |
        pip install pytest delocate wheel
        HYPER_WHEEL_LOC=$(ls -d python/dist/*)
        echo About to delocate $HYPER_WHEEL_LOC
        delocate-wheel -v $HYPER_WHEEL_LOC
        # delocate-wheel will copy all required libraries but
        # the tableauhyperapi also requires the hyperd executable
        # so we manually copy that into the wheel as a workaround
        python -m wheel unpack $HYPER_WHEEL_LOC
        # TODO: Don't hard code version here!!!
        cp -r deps/tableauhyperapi/lib/hyper hyperarrow-0.0.1.dev0/hyperarrow/.dylibs
        python -m wheel pack hyperarrow-0.0.1.dev0
    - name: Upload wheel
      uses: actions/upload-artifact@v2
      with:
        name: macos-${{ matrix.python-version }}
        path: ./*.whl
    - name: Test wheel
      run: |
        python -m pip install hyperarrow*.whl
        python -c "import hyperarrow; hyperarrow.test()"
