name: hyperarrow python wheels

on:
  release:
    types: [created, edited]
  workflow_dispatch:

jobs:
  build-macos:

    runs-on: macos-latest
    env:
      CTEST_OUTPUT_ON_FAILURE: 1
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: "3.10"
        activate-environment: hyperarrow
        channels: conda-forge
    - name: Download Hyper Library / Headers
      run: |
        mkdir deps
        pushd deps
        wget https://downloads.tableau.com/tssoftware/tableauhyperapi-cxx-macos-x86_64-release-hyperapi_release_26.0.0.13821.r1fbe38ce.zip -O tableauhyperapi.zip
        unzip tableauhyperapi.zip
        mv tableauhyperapi-cxx-macos-x86_64-release-hyperapi_release_26.0.0.13821.r1fbe38ce tableauhyperapi
        popd
    - name: Set up out of core build
      shell: bash -l {0}
      env:
        TABLEAU_CMAKE_PATH: "/Users/runner/work/hyperarrow/hyperarrow/deps/tableauhyperapi/share/cmake"
        MACOSX_DEPLOYMENT_TARGET: "10.9"
      run: |
        conda activate hyperarrow
        conda install -c conda-forge "arrow-cpp>=6.0" boost-cpp pyarrow
        mkdir build
        cd build
        cmake ..
        make
        make test
        make python
        cd ..
    - name: Fix wheel
      shell: bash -l {0}
      run: |
        conda activate hyperarrow
        conda install -c conda-forge pytest delocate
        delocate-wheel -v python/dist/*
    - name: Upload wheel
      uses: actions/upload-artifact@v2
      with:
        name: macos
        path: python/dist/*.whl
    - name: Test wheel
        python -m pip install python/dist/hyperarrow*
        python -c "import hyperarrow; hyperarrow.test()"
