name: hyperarrow tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
    - name: Install Arrow Libraries
      run: |
        sudo apt update
        sudo apt install -y -V ca-certificates lsb-release wget
        wget https://apache.jfrog.io/artifactory/arrow/$(lsb_release --id --short | tr 'A-Z' 'a-z')/apache-arrow-apt-source-latest-$(lsb_release --codename --short).deb
        sudo apt install -y -V ./apache-arrow-apt-source-latest-$(lsb_release --codename --short).deb
        sudo apt update
        sudo apt install -y -V libarrow-dev
    - name: Download Hyper Library / Headers
      run: |
        mkdir deps
        pushd deps
        pwd
        wget https://downloads.tableau.com/tssoftware/tableauhyperapi-cxx-linux-x86_64-release-hyperapi_release_26.0.0.13821.r1fbe38ce.zip -O tableauhyperapi.zip
        unzip tableauhyperapi.zip
        popd
    - name: Set up out of core build
      run: |
        mkdir build
        cd build
        pwd
        ls ../deps/tableauhyperapi/share/cmake
        export TABLEAU_CMAKE_PATH=../deps/tableauhyperapi/share/cmake
        cmake ..
        make
    - name: Run test suite
      run: make test